// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/globals/Avatar.vue')['default']
    DarkToggle: typeof import('./src/components/globals/DarkToggle.vue')['default']
    Header: typeof import('./src/components/blocks/Header.vue')['default']
    MetamaskConnect: typeof import('./src/components/globals/MetamaskConnect.vue')['default']
    SampleWalletData: typeof import('./src/components/cards/SampleWalletData.vue')['default']
  }
}

export { }
