// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/globals/Avatar.vue')['default']
    CardContainer: typeof import('./components/globals/CardContainer.vue')['default']
    DarkToggle: typeof import('./components/globals/DarkToggle.vue')['default']
    Header: typeof import('./components/blocks/Header.vue')['default']
    InputNumber: typeof import('./components/globals/InputNumber.vue')['default']
    InputText: typeof import('./components/globals/InputText.vue')['default']
    SampleWalletData: typeof import('./components/cards/SampleWalletData.vue')['default']
    WalletConnectButton: typeof import('./components/globals/wallet/WalletConnectButton.vue')['default']
    WalletDisconnectButton: typeof import('./components/globals/wallet/WalletDisconnectButton.vue')['default']
    WalletModal: typeof import('./components/globals/wallet/WalletModal.vue')['default']
    WalletProviderButton: typeof import('./components/globals/wallet/WalletProviderButton.vue')['default']
  }
}

export { }
